{
 "title": "eks-${{ values.observability_label }}-overview",
 "tags": [
  "eks_ingress",
  "${{values.eks_cluster_name}}",
  "vkpr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "container",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "K8S",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kubernetes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(${{ values.observability_label }}_kube_node_info)"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(${{ values.observability_label }}_kube_pod_info)"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(${{ values.observability_label }}_kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "Kubernetes Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${{ values.observability_label }}_kubernetes_build_info",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "ETCD Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${{ values.observability_label }}_etcd_server_version",
     "legendFormat": "{{ server_version }}"
    }
   ]
  },
  {
   "title": "ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(${{ values.observability_label }}_etcd_server_version)"
    }
   ]
  },
  {
   "title": "Abnormal Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((${{ values.observability_label }}_kube_node_status_condition{condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (${{ values.observability_label }}_kube_node_status_condition{condition!=\"Ready\", status=\"true\"} == 1)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((${{ values.observability_label }}_kube_pod_status_phase{phase!~\"Running|Succeeded\"} == 1) OR ON(namespace, pod) (${{ values.observability_label }}_kube_pod_status_ready{condition=\"true\"} == 0)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(${{ values.observability_label }}_kube_pod_container_status_running != 1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Container Runtime Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, ${{ values.observability_label }}_kube_node_info)",
     "legendFormat": "{{ container_runtime_version }}"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, ${{ values.observability_label }}_kubernetes_build_info)",
     "legendFormat": "{{ platform }}"
    }
   ]
  },
  {
   "title": "Leaderless ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(${{ values.observability_label }}_etcd_server_has_leader == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (${{ values.observability_label }}_node_filesystem_size_bytes{instance!=\"\"}) - sum (${{ values.observability_label }}_node_filesystem_free_bytes{instance!=\"\"})) / sum (${{ values.observability_label }}_node_filesystem_size_bytes{instance!=\"\"})"
    }
   ]
  },
  {
   "title": "$Node： Node memory details ",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "count(${{ values.observability_label }}_kube_pod_info) by (node)",
     "legendFormat": "pod core "
    },
    {
     "expr": "sum (irate(${{ values.observability_label }}_container_cpu_usage_seconds_total{container!=\"\"}[2m])) by (node)"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node!=\"\"}) by (node)"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node!=\"\"}) by (node)"
    },
    {
     "expr": "sum (${{ values.observability_label }}_container_memory_working_set_bytes{container!=\"\"}) by (node)"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"}) by (node) - 0"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"}) by (node)"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\"}) by (node)"
    },
    {
     "expr": "sum (${{ values.observability_label }}_container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) by (node)"
    },
    {
     "expr": "sum (${{ values.observability_label }}_container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}) by (node)"
    },
    {
     "expr": "sum (${{ values.observability_label }}_container_memory_working_set_bytes{container!=\"\"})by (node) / sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})by (node)",
     "legendFormat": " memory request %"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"})by (node) / sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})by (node)",
     "legendFormat": " Memory Usage %"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\"})by (node) / sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})by (node)",
     "legendFormat": " Network bandwidth %"
    },
    {
     "expr": "sum (irate(${{ values.observability_label }}_container_cpu_usage_seconds_total{container!=\"\"}[2m]))by (node) / sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})by (node)",
     "legendFormat": "CPU limit %"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"})by (node) / sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})by (node)",
     "legendFormat": "CPU max %"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\"})by (node) / sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})by (node)",
     "legendFormat": " Network bandwidth %"
    },
    {
     "expr": "sum (${{ values.observability_label }}_container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})by (node) / sum (${{ values.observability_label }}_container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})by (node)",
     "legendFormat": " English version %"
    },
    {
     "expr": "sum(${{ values.observability_label }}_kube_node_status_allocatable{resource=\"pods\", unit=\"integer\"})by (node)",
     "legendFormat": "Pod disk "
    }
   ]
  }
 ]
}