apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: via-cep-demo
  description: Consulte CEPs de todo o Brasil.
  publishedAt: 2022-11-25
  tags:
    - rest
    - api
    - change
spec:
  type: openapi
  lifecycle: production
  owner: consumer
  definition: |-
    openapi: 3.0.1
    info:
        title: ViaCEP
        description: Consulte CEPs de todo o Brasil.
        termsOfService: http://swagger.io/terms/
        contact:
            email: apiteam@swagger.io
        license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
        version: 1.0.0
    externalDocs:
        description: Find out more about Swagger
        url: http://swagger.io
    servers:
        - url: https://viacep.com.br/
    tags:
        - name: Address
          description: Getting zip-code informations
          externalDocs:
            description: Find out more
            url: http://swagger.io
    paths:
        '/ws/{zip-code}/json':
            get:
                tags:
                    - Address
                summary: Find Address by zip-code
                description: Returns a single Address
                operationId: getAddressByzip-code
                parameters:
                    - name: zip-code
                      in: path
                      description: zip-code to search
                      required: true
                      schema:
                        type: string
                responses:
                    '200':
                        description: successful operation
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Address'
                    '400':
                        description: Invalid zip-code supplied
                        content: {}
                    '404':
                        description: Address not found
                        content: {}
    components:
        schemas:
            Address:
                type: object
                properties:
                    cep:
                        type: string
                    logradouro:
                        type: string
                    complemento:
                        type: string
                    bairro:
                        type: string
                    localidade:
                        type: string
                    uf:
                        type: string
                    ibge:
                        type: string
                    gia:
                        type: string
                    ddd:
                        type: string
                    siafi:
                        type: string
