{
 "title": "Logging - ${{ values.componentId }}",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "${{ values.componentId }}",
  "vkpr",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"${{ values.componentId }}\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"${{ values.componentId }}\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=\"${{ values.componentId }}\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"${{ values.componentId }}\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (pod)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({app=\"${{ values.componentId }}\"} |~ \"(?i)$searchable_pattern\")[30s])) by (pod)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"${{ values.componentId }}\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container=\"$container\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  }
 ]
}